version: "3.9"

services:
  postgres:
    container_name: postgres
    image: postgres:13
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_USER}
    volumes:
      - users_data:/var/lib/postgresql/data

  backend:
    container_name: backend
    build:
      context: .
      dockerfile: ./Dockerfile
      target: development
    restart: unless-stopped
    ports:
      - ${PORT}:${PORT}
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_started
    volumes:
      - .:/usr/src/app/

volumes:
  users_data:
